### ISSUE TITLE
About version issues encountered in running code!

### ISSUE THREAD

**Issue by LitGreenhand** [AaronHeee/LLMs-as-Zero-Shot-Conversational-RecSys#1]
I want to ask about the fschat package used when running baize and vicuna models. When I run it, The program will say：
'from fastchat.conversation import get_default_conv_template, compute_skip_echo_len
ImportError: cannot import name 'get_default_conv_template' from 'fastchat.conversation' '. 
So I'd like to ask about the specific version of the fschat package and the corresponding torch version

**Comment by AaronHeee** [comment]
Hi @LitGreenhand, thanks for your interests in our work. It seems that these functions are deprecated in v0.2.28 ([source](https://urldefense.com/v3/__https://github.com/lm-sys/FastChat/commit/ea9123c86060f657d975b5cfffedf6e5d4357aeb__;!!Mih3wA!GSveUuV0FHg7oHPWPKhdNpPonb00mDfNvsTr-b9UvBR6pM65UzRk4mKEf8Ht2oEn6d3PI7i_5GSxcqXlpQ$)), I think older versions should work fine. Please let me know if there are any other issues.

**Comment by LitGreenhand** [comment]
Thank you for your reply @AaronHeee, But as for the version of fschat, I have just tried from v.0.2.20 to v0.2.32, during which the problem has not been solved. Could you ask about the specific version of fschat?

**Comment by AaronHeee** [comment]
Hi @LitGreenhand, my collaborator told me the version we used is 0.2.28. Please try this and let me know if there are any problems. If not, I would update the README.md file with this exact version to avoid confusion.

**Comment by AaronHeee** [comment]
As there are no activities, we close this issue.
